apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      app: frontend
      tier: frontend
      service: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
        service: frontend
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      serviceAccountName: frontend
      containers:
      - name: frontend
        image: "{{ .Values.frontend_image.name }}:{{ .Values.frontend_image.tag }}"
        imagePullPolicy: Always
        ports:
          - containerPort: 80
          

