---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80    
    targetPort: 80
  selector:
    app: frontend
    tier: frontend



