---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicasCount }}
  selector: 
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: "backend"
        image: "{{ .Values.backend_image.name }}:{{ .Values.backend_image.tag }}"
        ports: 
        - containerPort: 8080
        env:
        - name: "PG_HOST"
          value: {{ .Values.postgres.host }}
        - name: "PG_PORT"
          value: {{ .Values.postgres.port }}
        - name: "PG_DB_NAME"
          value: {{ .Values.postgres.db_name }}
        - name: "PG_USER"
          valueFrom:
            secretKeyRef:
              name: pg-user-pass
              key: username
        - name: "PG_PASS"      
          valueFrom:
            secretKeyRef:
              name: pg-user-pass
              key: password
        - name: "REDIS_HOST"
          value: "localhost"
        - name: "REDIS_PORT"
          value: {{ .Values.redis.host }}
        - name: "MONGO_HOST"
          value: {{ .Values.mongodb.host }}
        - name: "MONGO_PORT"
          value: {{ .Values.mongodb.port }}
        - name: "MONGO_DB_NAME"
          value: {{ .Values.mongodb.db_name }}
      - name: "redis"
        image: "redis:7-alpine"
      - name: "postgresql"
        image: "postgres:14-alpine"
        env:
        - name: "POSTGRES_DB"
          value: {{ .Values.postgres.db_name}}
        - name: "POSTGRES_USER"
          valueFrom:
            secretKeyRef:
              name: pg-user-pass
              key: username
        - name: "POSTGRES_PASSWORD"      
          valueFrom:
            secretKeyRef:
              name: pg-user-pass
              key: password



                  
